<?php
// Add this at the top of your PHP script.
error_reporting(E_ALL);
ini_set('display_errors', 1);

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

include_once 'env.php';




// System configeration
$notification_icons = array(
    'To-Dos' => 'fas fa-boxes',
    'To-Dos1' => 'fas fa-user-md'
);
$notification_icons_json = json_encode($notification_icons);
// to javascript




// Define an array of country codes and names
$countryCodes = [
    ['id' => 1, 'flag' => '🇦🇫', 'code' => '+93', 'name' => 'Afghanistan', 'lang' => 'Pashto/Dari'],
    ['id' => 2, 'flag' => '🇦🇱', 'code' => '+355', 'name' => 'Albania', 'lang' => 'Albanian'],
    ['id' => 3, 'flag' => '🇩🇿', 'code' => '+213', 'name' => 'Algeria', 'lang' => 'Arabic/Berber'],
    ['id' => 4, 'flag' => '🇦🇩', 'code' => '+376', 'name' => 'Andorra', 'lang' => 'Catalan'],
    ['id' => 5, 'flag' => '🇦🇴', 'code' => '+244', 'name' => 'Angola', 'lang' => 'Portuguese'],
    ['id' => 6, 'flag' => '🇦🇬', 'code' => '+1-268', 'name' => 'Antigua and Barbuda', 'lang' => 'English'],
    ['id' => 7, 'flag' => '🇦🇷', 'code' => '+54', 'name' => 'Argentina', 'lang' => 'Spanish'],
    ['id' => 8, 'flag' => '🇦🇲', 'code' => '+374', 'name' => 'Armenia', 'lang' => 'Armenian'],
    ['id' => 9, 'flag' => '🇦🇺', 'code' => '+61', 'name' => 'Australia', 'lang' => 'English'],
    ['id' => 10, 'flag' => '🇦🇹', 'code' => '+43', 'name' => 'Austria', 'lang' => 'German'],
    ['id' => 11, 'flag' => '🇦🇿', 'code' => '+994', 'name' => 'Azerbaijan', 'lang' => 'Azerbaijani'],
    ['id' => 12, 'flag' => '🇧🇸', 'code' => '+1-242', 'name' => 'Bahamas', 'lang' => 'English'],
    ['id' => 13, 'flag' => '🇧🇭', 'code' => '+973', 'name' => 'Bahrain', 'lang' => 'Arabic'],
    ['id' => 14, 'flag' => '🇧🇩', 'code' => '+880', 'name' => 'Bangladesh', 'lang' => 'Bengali'],
    ['id' => 15, 'flag' => '🇧🇧', 'code' => '+1-246', 'name' => 'Barbados', 'lang' => 'English'],
    ['id' => 16, 'flag' => '🇧🇾', 'code' => '+375', 'name' => 'Belarus', 'lang' => 'Belarusian/Russian'],
    ['id' => 17, 'flag' => '🇧🇪', 'code' => '+32', 'name' => 'Belgium', 'lang' => 'Dutch/French/German'],
    ['id' => 18, 'flag' => '🇧🇿', 'code' => '+501', 'name' => 'Belize', 'lang' => 'English'],
    ['id' => 19, 'flag' => '🇧🇯', 'code' => '+229', 'name' => 'Benin', 'lang' => 'French'],
    ['id' => 20, 'flag' => '🇧🇹', 'code' => '+975', 'name' => 'Bhutan', 'lang' => 'Dzongkha'],
    ['id' => 21, 'flag' => '🇧🇴', 'code' => '+591', 'name' => 'Bolivia', 'lang' => 'Spanish/Quechua/Aymara'],
    ['id' => 22, 'flag' => '🇧🇦', 'code' => '+387', 'name' => 'Bosnia and Herzegovina', 'lang' => 'Bosnian/Croatian/Serbian'],
    ['id' => 23, 'flag' => '🇧🇼', 'code' => '+267', 'name' => 'Botswana', 'lang' => 'English/Tswana'],
    ['id' => 24, 'flag' => '🇧🇷', 'code' => '+55', 'name' => 'Brazil', 'lang' => 'Portuguese'],
    ['id' => 25, 'flag' => '🇧🇳', 'code' => '+673', 'name' => 'Brunei', 'lang' => 'Malay'],
    ['id' => 26, 'flag' => '🇧🇬', 'code' => '+359', 'name' => 'Bulgaria', 'lang' => 'Bulgarian'],
    ['id' => 27, 'flag' => '🇧🇫', 'code' => '+226', 'name' => 'Burkina Faso', 'lang' => 'French'],
    ['id' => 28, 'flag' => '🇧🇮', 'code' => '+257', 'name' => 'Burundi', 'lang' => 'Kirundi/French/English'],
    ['id' => 29, 'flag' => '🇰🇭', 'code' => '+855', 'name' => 'Cambodia', 'lang' => 'Khmer'],
    ['id' => 30, 'flag' => '🇨🇲', 'code' => '+237', 'name' => 'Cameroon', 'lang' => 'English/French'],
    ['id' => 31, 'flag' => '🇨🇦', 'code' => '+1', 'name' => 'Canada', 'lang' => 'English/French'],
    ['id' => 32, 'flag' => '🇨🇻', 'code' => '+238', 'name' => 'Cape Verde', 'lang' => 'Portuguese'],
    ['id' => 33, 'flag' => '🇨🇫', 'code' => '+236', 'name' => 'Central African Republic', 'lang' => 'French/Sango'],
    ['id' => 34, 'flag' => '🇹🇩', 'code' => '+235', 'name' => 'Chad', 'lang' => 'French/Arabic'],
    ['id' => 35, 'flag' => '🇨🇱', 'code' => '+56', 'name' => 'Chile', 'lang' => 'Spanish'],
    ['id' => 36, 'flag' => '🇨🇳', 'code' => '+86', 'name' => 'China', 'lang' => 'Chinese'],
    ['id' => 37, 'flag' => '🇨🇴', 'code' => '+57', 'name' => 'Colombia', 'lang' => 'Spanish'],
    ['id' => 38, 'flag' => '🇰🇲', 'code' => '+269', 'name' => 'Comoros', 'lang' => 'Arabic/French/Comorian'],
    ['id' => 39, 'flag' => '🇨🇩', 'code' => '+243', 'name' => 'Congo (DRC)', 'lang' => 'French'],
    ['id' => 40, 'flag' => '🇨🇬', 'code' => '+242', 'name' => 'Congo (Republic)', 'lang' => 'French'],
    ['id' => 41, 'flag' => '🇨🇷', 'code' => '+506', 'name' => 'Costa Rica', 'lang' => 'Spanish'],
    ['id' => 42, 'flag' => '🇭🇷', 'code' => '+385', 'name' => 'Croatia', 'lang' => 'Croatian'],
    ['id' => 43, 'flag' => '🇨🇮', 'code' => '+225', 'name' => 'Côte d\'Ivoire (Ivory Coast)', 'lang' => 'French'],
    ['id' => 44, 'flag' => '🇨🇷', 'code' => '+506', 'name' => 'Costa Rica', 'lang' => 'Spanish'],
    ['id' => 45, 'flag' => '🇨🇾', 'code' => '+357', 'name' => 'Cyprus', 'lang' => 'Greek/Turkish'],
    ['id' => 46, 'flag' => '🇨🇿', 'code' => '+420', 'name' => 'Czech Republic (Czechia)', 'lang' => 'Czech'],
    ['id' => 47, 'flag' => '🇩🇰', 'code' => '+45', 'name' => 'Denmark', 'lang' => 'Danish'],
    ['id' => 48, 'flag' => '🇩🇯', 'code' => '+253', 'name' => 'Djibouti', 'lang' => ['Arabic/French']],
    ['id' => 49, 'flag' => '🇩🇲', 'code' => '+1-767', 'name' => 'Dominica', 'lang' => 'English'],
    ['id' => 50, 'flag' => '🇩🇴', 'code' => '+1-809/829/849', 'name' => 'Dominican Republic', 'lang' => 'Spanish'],
    ['id' => 51, 'flag' => '🇪🇨', 'code' => '+593', 'name' => 'Ecuador', 'lang' => 'Spanish'],
    ['id' => 52, 'flag' => '🇪🇬', 'code' => '+20', 'name' => 'Egypt', 'lang' => ['Arabic']],
    ['id' => 53, 'flag' => '🇸🇻', 'code' => '+503', 'name' => 'El Salvador', 'lang' => ['Spanish']],
    ['id' => 54, 'flag' => '🇬🇶', 'code' => '+240', 'name' => 'Equatorial Guinea', 'lang' => ['Spanish/French/Portuguese']],
    ['id' => 55, 'flag' => '🇪🇷', 'code' => '+291', 'name' => 'Eritrea', 'lang' => ['Tigrinya/Arabic/English']],
    ['id' => 56, 'flag' => '🇪🇪', 'code' => '+372', 'name' => 'Estonia', 'lang' => ['Estonian']],
    ['id' => 57, 'flag' => '🇪🇹', 'code' => '+251', 'name' => 'Ethiopia', 'lang' => ['Amharic']],
    ['id' => 58, 'flag' => '🇫🇰', 'code' => '+500', 'name' => 'Falkland Islands', 'lang' => ['English']],
    ['id' => 59, 'flag' => '🇫🇴', 'code' => '+298', 'name' => 'Faroe Islands', 'lang' => ['Faroese/English']],
    ['id' => 60, 'flag' => '🇫🇯', 'code' => '+679', 'name' => 'Fiji', 'lang' => ['Fijian/English/Hindi']],
    ['id' => 61, 'flag' => '🇫🇮', 'code' => '+358', 'name' => 'Finland', 'lang' => ['Finnish/Swedish']],
    ['id' => 62, 'flag' => '🇫🇷', 'code' => '+33', 'name' => 'France', 'lang' => ['French']],
    ['id' => 63, 'flag' => '🇬🇫', 'code' => '+594', 'name' => 'French Guiana', 'lang' => ['French']],
    ['id' => 64, 'flag' => '🇵🇫', 'code' => '+689', 'name' => 'French Polynesia', 'lang' => ['French']],
    ['id' => 65, 'flag' => '🇬🇦', 'code' => '+241', 'name' => 'Gabon', 'lang' => ['French']],
    ['id' => 66, 'flag' => '🇬🇲', 'code' => '+220', 'name' => 'Gambia', 'lang' => ['English']],
    ['id' => 67, 'flag' => '🇬🇪', 'code' => '+995', 'name' => 'Georgia', 'lang' => ['Georgian']],
    ['id' => 68, 'flag' => '🇩🇪', 'code' => '+49', 'name' => 'Germany', 'lang' => ['German']],
    ['id' => 69, 'flag' => '🇬🇭', 'code' => '+233', 'name' => 'Ghana', 'lang' => ['English']],
    ['id' => 70, 'flag' => '🇬🇮', 'code' => '+350', 'name' => 'Gibraltar', 'lang' => ['English']],
    ['id' => 71, 'flag' => '🇬🇷', 'code' => '+30', 'name' => 'Greece', 'lang' => ['Greek']],
    ['id' => 72, 'flag' => '🇬🇱', 'code' => '+299', 'name' => "Greenland", "lang" => 'Greenlandic/Danish'],
    ['id' => 73, 'flag' => '🇬🇩', 'code' => '+1-473', 'name' => 'Grenada', 'lang' => ['English']],
    ['id' => 74, 'flag' => '🇬🇵', 'code' => '+590', 'name' => 'Guadeloupe', 'lang' => ['French']],
    ['id' => 75, 'flag' => '🇬🇺', 'code' => '+1-671', 'name' => 'Guam', 'lang' => ['English/Chamorro']],
    ['id' => 76, 'flag' => '🇬🇹', 'code' => '+502', 'name' => 'Guatemala', 'lang' => ['Spanish']],
    ['id' => 77, 'flag' => '🇬🇬', 'code' => '+44-1481', 'name' => 'Guernsey', 'lang' => ['English']],
    ['id' => 78, 'flag' => '🇬🇳', 'code' => '+224', 'name' => 'Guinea', 'lang' => ['French']],
    ['id' => 79, 'flag' => '🇬🇼', 'code' => '+245', 'name' => "Guinea-Bissau", "lang" => 'Portuguese'],
    ['id' => 80, 'flag' => '🇬🇾', 'code' => '+592', 'name' => "Guyana", "lang" => 'English'],
    ['id' => 81, 'flag' => '🇭🇹', 'code' => '+509', 'name' => "Haiti", "lang" => 'Haitian Creole/French'],
    ['id' => 82, 'flag' => '🇭🇳', 'code' => '+504', 'name' => 'Honduras', 'lang' => ['Spanish']],
    ['id' => 83, 'flag' => '🇭🇰', 'code' => '+852', 'name' => 'Hong Kong', 'lang' => ['Chinese/English']],
    ['id' => 84, 'flag' => '🇭🇺', 'code' => '+36', 'name' => 'Hungary', 'lang' => ['Hungarian']],
    ['id' => 85, 'flag' => '🇮🇸', 'code' => '+354', 'name' => 'Iceland', 'lang' => ['Icelandic']],
    ['id' => 86, 'flag' => '🇮🇳', 'code' => '+91', 'name' => 'India', 'lang' => ['Hindi/English']],
    ['id' => 87, 'flag' => '🇮🇩', 'code' => '+62', 'name' => 'Indonesia', 'lang' => ['Indonesian']],
    ['id' => 88, 'flag' => '🇮🇷', 'code' => '+98', 'name' => 'Iran', 'lang' => ['Persian']],
    ['id' => 89, 'flag' => '🇮🇶', 'code' => '+964', 'name' => 'Iraq', 'lang' => ['Arabic/Kurdish']],
    ['id' => 90, 'flag' => '🇮🇪', 'code' => '+353', 'name' => "Ireland", "lang" => 'Irish/English'],
    ['id' => 92, 'flag' => '🇯🇵', 'code' => '+81', 'name' => 'Japan', 'lang' => ['Japanese']],
    ['id' => 93, 'flag' => '🇰🇪', 'code' => '+254', 'name' => 'Kenya', 'lang' => ['English', 'Swahili']],
    ['id' => 94, 'flag' => '🇰🇼', 'code' => '+965', 'name' => 'Kuwait', 'lang' => ['Arabic']],
    ['id' => 95, 'flag' => '🇱🇰', 'code' => '+94', 'name' => 'Sri Lanka', 'lang' => ['Sinhala', 'Tamil']],
    ['id' => 96, 'flag' => '🇱🇸', 'code' => '+266', 'name' => 'Lesotho', 'lang' => ['Sesotho']],
    ['id' => 97, 'flag' => '🇱🇸', 'code' => '+352', 'name' => 'Luxembourg', 'lang' => ['Luxembourgish', 'French', 'German']],
    ['id' => 98, 'flag' => '🇲🇾', 'code' => '+60', 'name' => 'Malaysia', 'lang' => ['Malay']],
    ['id' => 99, 'flag' => '🇲🇻', 'code' => '+960', 'name' => 'Maldives', 'lang' => ['Dhivehi']],
    ['id' => 100, 'flag' => '🇲🇱', 'code' => '+223', 'name' => 'Mali', 'lang' => ['French']],
    ['id' => 101, 'flag' => '🇱🇦', 'code' => '+856', 'name' => 'Laos', 'lang' => ['Lao']],
    ['id' => 102, 'flag' => '🇱🇻', 'code' => '+371', 'name' => 'Latvia', 'lang' => ['Latvian']],
    ['id' => 103, 'flag' => '🇱🇧', 'code' => '+961', 'name' => 'Lebanon', 'lang' => ['Arabic']],
    ['id' => 104, 'flag' => '🇱🇸', 'code' => '+266', 'name' => 'Lesotho', 'lang' => ['Sesotho', 'English']],
    ['id' => 105, 'flag' => '🇱🇷', 'code' => '+231', 'name' => 'Liberia', 'lang' => ['English']],
    ['id' => 106, 'flag' => '🇱🇾', 'code' => '+218', 'name' => 'Libya', 'lang' => ['Arabic']],
    ['id' => 107, 'flag' => '🇱🇮', 'code' => '+423', 'name' => 'Liechtenstein', 'lang' => ['German']],
    ['id' => 108, 'flag' => '🇱🇹', 'code' => '+370', 'name' => 'Lithuania', 'lang' => ['Lithuanian']],
    ['id' => 109, 'flag' => '🇱🇺', 'code' => '+352', 'name' => 'Luxembourg', 'lang' => ['Luxembourgish', 'French', 'German']],
    ['id' => 110, 'flag' => '🇲🇴', 'code' => '+853', 'name' => 'Macau', 'lang' => ['Chinese', 'Portuguese']],
    ['id' => 111, 'flag' => '🇲🇰', 'code' => '+389', 'name' => 'North Macedonia', 'lang' => ['Macedonian']],
    ['id' => 112, 'flag' => '🇲🇬', 'code' => '+261', 'name' => 'Madagascar', 'lang' => ['Malagasy', 'French']],
    ['id' => 113, 'flag' => '🇲🇼', 'code' => '+265', 'name' => 'Malawi', 'lang' => ['English', 'Chichewa']],
    ['id' => 114, 'flag' => '🇲🇾', 'code' => '+60', 'name' => 'Malaysia', 'lang' => ['Malay']],
    ['id' => 115, 'flag' => '🇲🇻', 'code' => '+960', 'name' => 'Maldives', 'lang' => ['Dhivehi']],
    ['id' => 116, 'flag' => '🇲🇱', 'code' => '+223', 'name' => 'Mali', 'lang' => ['French']],
    ['id' => 117, 'flag' => '🇲🇹', 'code' => '+356', 'name' => 'Malta', 'lang' => ['Maltese', 'English']],
    ['id' => 118, 'flag' => '🇲🇭', 'code' => '+692', 'name' => 'Marshall Islands', 'lang' => ['Marshallese', 'English']],
    ['id' => 119, 'flag' => '🇲🇷', 'code' => '+222', 'name' => 'Mauritania', 'lang' => ['Arabic']],
    ['id' => 120, 'flag' => '🇲🇺', 'code' => '+230', 'name' => 'Mauritius', 'lang' => ['English', 'French']],
    ['id' => 121, 'flag' => '🇲🇽', 'code' => '+52', 'name' => 'Mexico', 'lang' => ['Spanish']],
    ['id' => 122, 'flag' => '🇫🇲', 'code' => '+691', 'name' => 'Micronesia', 'lang' => ['English']],
    ['id' => 123, 'flag' => '🇲🇩', 'code' => '+373', 'name' => 'Moldova', 'lang' => ['Romanian']],
    ['id' => 124, 'flag' => '🇲🇨', 'code' => '+377', 'name' => 'Monaco', 'lang' => ['French']],
    ['id' => 125, 'flag' => '🇲🇳', 'code' => '+976', 'name' => 'Mongolia', 'lang' => ['Mongolian']],
    ['id' => 126, 'flag' => '🇲🇪', 'code' => '+382', 'name' => 'Montenegro', 'lang' => ['Montenegrin']],
    ['id' => 127, 'flag' => '🇲🇦', 'code' => '+212', 'name' => 'Morocco', 'lang' => ['Arabic', 'Berber']],
    ['id' => 128, 'flag' => '🇲🇿', 'code' => '+258', 'name' => 'Mozambique', 'lang' => ['Portuguese']],
    ['id' => 129, 'flag' => '🇲🇲', 'code' => '+95', 'name' => 'Myanmar', 'lang' => ['Burmese']],
    ['id' => 130, 'flag' => '🇳🇦', 'code' => '+264', 'name' => 'Namibia', 'lang' => ['English']],
    ['id' => 131, 'flag' => '🇳🇷', 'code' => '+674', 'name' => 'Nauru', 'lang' => ['Nauruan', 'English']],
    ['id' => 132, 'flag' => '🇳🇵', 'code' => '+977', 'name' => 'Nepal', 'lang' => ['Nepali']],
    ['id' => 133, 'flag' => '🇳🇱', 'code' => '+31', 'name' => 'Netherlands', 'lang' => ['Dutch']],
    ['id' => 134, 'flag' => '🇳🇿', 'code' => '+64', 'name' => 'New Zealand', 'lang' => ['English', 'Maori']],
    ['id' => 135, 'flag' => '🇳🇮', 'code' => '+505', 'name' => 'Nicaragua', 'lang' => ['Spanish']],
    ['id' => 136, 'flag' => '🇳🇪', 'code' => '+227', 'name' => 'Niger', 'lang' => ['French']],
    ['id' => 137, 'flag' => '🇳🇬', 'code' => '+234', 'name' => 'Nigeria', 'lang' => ['English']],
    ['id' => 138, 'flag' => '🇳🇺', 'code' => '+683', 'name' => 'Niue', 'lang' => ['Niuean', 'English']],
    ['id' => 139, 'flag' => '🇳🇫', 'code' => '+672', 'name' => 'Norfolk Island', 'lang' => ['English']],
    ['id' => 140, 'flag' => '🇰🇵', 'code' => '+850', 'name' => 'North Korea', 'lang' => ['Korean']],
    ['id' => 141, 'flag' => '🇲🇰', 'code' => '+389', 'name' => 'North Macedonia', 'lang' => ['Macedonian']],
    ['id' => 142, 'flag' => '🇲🇵', 'code' => '+1 670', 'name' => 'Northern Mariana Islands', 'lang' => ['English', 'Chamorro']],
    ['id' => 143, 'flag' => '🇳🇴', 'code' => '+47', 'name' => 'Norway', 'lang' => ['Norwegian']],
    ['id' => 144, 'flag' => '🇴🇲', 'code' => '+968', 'name' => 'Oman', 'lang' => ['Arabic']],
    ['id' => 145, 'flag' => '🇵🇰', 'code' => '+92', 'name' => 'Pakistan', 'lang' => ['Urdu', 'English']],
    ['id' => 146, 'flag' => '🇵🇼', 'code' => '+680', 'name' => 'Palau', 'lang' => ['Palauan', 'English']],
    ['id' => 147, 'flag' => '🇵🇸', 'code' => '+970', 'name' => 'Palestine', 'lang' => ['Arabic']],
    ['id' => 148, 'flag' => '🇵🇦', 'code' => '+507', 'name' => 'Panama', 'lang' => ['Spanish']],
    ['id' => 149, 'flag' => '🇵🇬', 'code' => '+675', 'name' => 'Papua New Guinea', 'lang' => ['English', 'Tok Pisin', 'Hiri Motu']],
    ['id' => 150, 'flag' => '🇵🇾', 'code' => '+595', 'name' => 'Paraguay', 'lang' => ['Spanish', 'Guarani']],
    ['id' => 151, 'flag' => '🇵🇪', 'code' => '+51', 'name' => 'Peru', 'lang' => ['Spanish', 'Quechua', 'Aymara']],
    ['id' => 152, 'flag' => '🇵🇭', 'code' => '+63', 'name' => 'Philippines', 'lang' => ['Filipino', 'English']],
    ['id' => 153, 'flag' => '🇵🇱', 'code' => '+48', 'name' => 'Poland', 'lang' => ['Polish']],
    ['id' => 154, 'flag' => '🇵🇹', 'code' => '+351', 'name' => 'Portugal', 'lang' => ['Portuguese']],
    ['id' => 155, 'flag' => '🇵🇷', 'code' => '+1 787/939', 'name' => 'Puerto Rico', 'lang' => ['Spanish', 'English']],
    ['id' => 156, 'flag' => '🇶🇦', 'code' => '+974', 'name' => 'Qatar', 'lang' => ['Arabic']],
    ['id' => 157, 'flag' => '🇷🇴', 'code' => '+40', 'name' => 'Romania', 'lang' => ['Romanian']],
    ['id' => 158, 'flag' => '🇷🇺', 'code' => '+7', 'name' => 'Russia', 'lang' => ['Russian']],
    ['id' => 159, 'flag' => '🇷🇼', 'code' => '+250', 'name' => 'Rwanda', 'lang' => ['Kinyarwanda', 'French', 'English']],
    ['id' => 160, 'flag' => '🇰🇳', 'code' => '+1-869', 'name' => 'Saint Kitts and Nevis', 'lang' => ['English']],
    ['id' => 161, 'flag' => '🇱🇨', 'code' => '+1-758', 'name' => 'Saint Lucia', 'lang' => ['English']],
    ['id' => 162, 'flag' => '🇻🇨', 'code' => '+1-784', 'name' => 'Saint Vincent and the Grenadines', 'lang' => ['English']],
    ['id' => 163, 'flag' => '🇼🇸', 'code' => '+685', 'name' => 'Samoa', 'lang' => ['Samoan', 'English']],
    ['id' => 164, 'flag' => '🇸🇲', 'code' => '+378', 'name' => 'San Marino', 'lang' => ['Italian']],
    ['id' => 165, 'flag' => '🇸🇹', 'code' => '+239', 'name' => 'Sao Tome and Principe', 'lang' => ['Portuguese']],
    ['id' => 166, 'flag' => '🇸🇦', 'code' => '+966', 'name' => 'Saudi Arabia', 'lang' => ['Arabic']],
    ['id' => 167, 'flag' => '🇸🇳', 'code' => '+221', 'name' => 'Senegal', 'lang' => ['French']],
    ['id' => 168, 'flag' => '🇷🇸', 'code' => '+381', 'name' => 'Serbia', 'lang' => ['Serbian']],
    ['id' => 169, 'flag' => '🇸🇨', 'code' => '+248', 'name' => 'Seychelles', 'lang' => ['Creole', 'English', 'French']],
    ['id' => 170, 'flag' => '🇸🇱', 'code' => '+232', 'name' => 'Sierra Leone', 'lang' => ['English']],
    ['id' => 171, 'flag' => '🇸🇬', 'code' => '+65', 'name' => 'Singapore', 'lang' => ['English', 'Malay', 'Mandarin', 'Tamil']],
    ['id' => 172, 'flag' => '🇸🇰', 'code' => '+421', 'name' => 'Slovakia', 'lang' => ['Slovak']],
    ['id' => 173, 'flag' => '🇸🇮', 'code' => '+386', 'name' => 'Slovenia', 'lang' => ['Slovene']],
    ['id' => 174, 'flag' => '🇸🇧', 'code' => '+677', 'name' => 'Solomon Islands', 'lang' => ['English']],
    ['id' => 175, 'flag' => '🇸🇴', 'code' => '+252', 'name' => 'Somalia', 'lang' => ['Somali', 'Arabic']],
    ['id' => 176, 'flag' => '🇿🇦', 'code' => '+27', 'name' => 'South Africa', 'lang' => ['Zulu', 'Xhosa', 'Afrikaans', 'English']],
    ['id' => 177, 'flag' => '🇸🇸', 'code' => '+211', 'name' => 'South Sudan', 'lang' => ['English']],
    ['id' => 178, 'flag' => '🇪🇸', 'code' => '+34', 'name' => 'Spain', 'lang' => ['Spanish']],
    ['id' => 179, 'flag' => '🇱🇰', 'code' => '+94', 'name' => 'Sri Lanka', 'lang' => ['Sinhala', 'Tamil']],
    ['id' => 180, 'flag' => '🇸🇩', 'code' => '+249', 'name' => 'Sudan', 'lang' => ['Arabic', 'English']],
    ['id' => 181, 'flag' => '🇸🇷', 'code' => '+597', 'name' => 'Suriname', 'lang' => ['Dutch']],
    ['id' => 182, 'flag' => '🇸🇪', 'code' => '+46', 'name' => 'Sweden', 'lang' => ['Swedish']],
    ['id' => 183, 'flag' => '🇨🇭', 'code' => '+41', 'name' => 'Switzerland', 'lang' => ['German', 'French', 'Italian', 'Romansh']],
    ['id' => 184, 'flag' => '🇸🇾', 'code' => '+963', 'name' => 'Syria', 'lang' => ['Arabic']],
    ['id' => 185, 'flag' => '🇹🇼', 'code' => '+886', 'name' => 'Taiwan', 'lang' => ['Mandarin']],
    ['id' => 186, 'flag' => '🇹🇯', 'code' => '+992', 'name' => 'Tajikistan', 'lang' => ['Tajik']],
    ['id' => 187, 'flag' => '🇹🇿', 'code' => '+255', 'name' => 'Tanzania', 'lang' => ['Swahili', 'English']],
    ['id' => 188, 'flag' => '🇹🇭', 'code' => '+66', 'name' => 'Thailand', 'lang' => ['Thai']],
    ['id' => 189, 'flag' => '🇹🇱', 'code' => '+670', 'name' => 'Timor-Leste', 'lang' => ['Tetum', 'Portuguese']],
    ['id' => 190, 'flag' => '🇹🇬', 'code' => '+228', 'name' => 'Togo', 'lang' => ['French']],
    ['id' => 191, 'flag' => '🇹🇴', 'code' => '+676', 'name' => 'Tonga', 'lang' => ['Tongan', 'English']],
    ['id' => 192, 'flag' => '🇹🇹', 'code' => '+1-868', 'name' => 'Trinidad and Tobago', 'lang' => ['English']],
    ['id' => 193, 'flag' => '🇹🇳', 'code' => '+216', 'name' => 'Tunisia', 'lang' => ['Arabic']],
    ['id' => 194, 'flag' => '🇹🇷', 'code' => '+90', 'name' => 'Turkey', 'lang' => ['Turkish']],
    ['id' => 195, 'flag' => '🇹🇲', 'code' => '+993', 'name' => 'Turkmenistan', 'lang' => ['Turkmen']],
    ['id' => 196, 'flag' => '🇹🇻', 'code' => '+688', 'name' => 'Tuvalu', 'lang' => ['Tuvaluan', 'English']],
    ['id' => 197, 'flag' => '🇺🇬', 'code' => '+256', 'name' => 'Uganda', 'lang' => ['English', 'Swahili']],
    ['id' => 198, 'flag' => '🇺🇦', 'code' => '+380', 'name' => 'Ukraine', 'lang' => ['Ukrainian']],
    ['id' => 199, 'flag' => '🇦🇪', 'code' => '+971', 'name' => 'United Arab Emirates', 'lang' => ['Arabic']],
    ['id' => 200, 'flag' => '🇬🇧', 'code' => '+44', 'name' => 'United Kingdom', 'lang' => ['English']],
    ['id' => 201, 'flag' => '🇺🇸', 'code' => '+1', 'name' => 'United States', 'lang' => ['English']],
    ['id' => 202, 'flag' => '🇺🇾', 'code' => '+598', 'name' => 'Uruguay', 'lang' => ['Spanish']],
    ['id' => 203, 'flag' => '🇺🇿', 'code' => '+998', 'name' => 'Uzbekistan', 'lang' => ['Uzbek']],
    ['id' => 204, 'flag' => '🇻🇺', 'code' => '+678', 'name' => 'Vanuatu', 'lang' => ['Bislama', 'English', 'French']],
    ['id' => 205, 'flag' => '🇻🇦', 'code' => '+379', 'name' => 'Vatican City', 'lang' => ['Italian', 'Latin']],
    ['id' => 206, 'flag' => '🇻🇪', 'code' => '+58', 'name' => 'Venezuela', 'lang' => ['Spanish']],
    ['id' => 207, 'flag' => '🇻🇳', 'code' => '+84', 'name' => 'Vietnam', 'lang' => ['Vietnamese']],
    ['id' => 208, 'flag' => '🇾🇪', 'code' => '+967', 'name' => 'Yemen', 'lang' => ['Arabic']],
    ['id' => 209, 'flag' => '🇿🇲', 'code' => '+260', 'name' => 'Zambia', 'lang' => ['English']],
    ['id' => 210, 'flag' => '🇿🇼', 'code' => '+263', 'name' => 'Zimbabwe', 'lang' => ['English', 'Shona', 'Sindebele']]
];
